import { PrismaClient, Plan, VerificationStatus, PartnerRole, AvailabilityType, InvestmentRange, BusinessType } from "@prisma/client"

const prisma = new PrismaClient()

const fakeUsers = [
  {
    name: "Rafael Mendonça",
    email: "rafael.mendonca@fake.socion.app",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "CTO & Co-founder | Ex-Nubank | 10 anos em fintech",
      location: "São Paulo, SP",
      bio: "Engenheiro de software com passagem pelo Nubank e Stone. Busco sócio de negócios com perfil comercial para co-fundar uma fintech B2B voltada para PMEs. Tenho o produto e a tecnologia, preciso de alguém que abra portas.",
      trustScore: 87,
      identityScore: 95,
      experienceScore: 90,
      competenceScore: 85,
      reputationScore: 80,
      commitmentScore: 85,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.SALES, PartnerRole.MARKETING],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.UP_TO_50K,
      seekingBusinessType: [BusinessType.SAAS, BusinessType.MARKETPLACE],
      offeringRole: [PartnerRole.TECHNOLOGY, PartnerRole.PRODUCT],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.UP_TO_10K,
      offeringBusinessType: [BusinessType.SAAS],
      weeklyHours: 40,
    },
  },
  {
    name: "Camila Torres",
    email: "camila.torres@fake.socion.app",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "Head de Growth | Ex-iFood | Especialista em PLG",
      location: "São Paulo, SP",
      bio: "Cresci produtos de 0 a 1M de usuários no iFood e na Creditas. Tenho obsessão por dados e experimentação. Procuro sócio técnico para construir um produto SaaS na vertical de RH. Invisto tempo e tenho savings para os primeiros 6 meses.",
      trustScore: 82,
      identityScore: 90,
      experienceScore: 88,
      competenceScore: 78,
      reputationScore: 75,
      commitmentScore: 82,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY, PartnerRole.PRODUCT],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.UP_TO_50K,
      seekingBusinessType: [BusinessType.SAAS],
      offeringRole: [PartnerRole.MARKETING, PartnerRole.SALES],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.UP_TO_50K,
      offeringBusinessType: [BusinessType.SAAS],
      weeklyHours: 40,
    },
  },
  {
    name: "Bruno Castilho",
    email: "bruno.castilho@fake.socion.app",
    image: "https://randomuser.me/api/portraits/men/67.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "CFO & Investidor Anjo | 3 exits | Especialista em M&A",
      location: "Curitiba, PR",
      bio: "Participei de 3 exits como CFO, o maior deles R$120M. Hoje atuo como investidor anjo e busco projetos early-stage com tração. Além de capital (até R$250k), trago network e mentoria financeira.",
      trustScore: 91,
      identityScore: 98,
      experienceScore: 92,
      competenceScore: 88,
      reputationScore: 90,
      commitmentScore: 88,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY, PartnerRole.PRODUCT],
      seekingAvailability: AvailabilityType.PART_TIME,
      seekingInvestment: InvestmentRange.ABOVE_50K,
      seekingBusinessType: [BusinessType.SAAS, BusinessType.MARKETPLACE, BusinessType.AI],
      offeringRole: [PartnerRole.FINANCE, PartnerRole.OPERATIONS],
      offeringAvailability: AvailabilityType.PART_TIME,
      offeringInvestment: InvestmentRange.ABOVE_50K,
      offeringBusinessType: [BusinessType.SAAS, BusinessType.MARKETPLACE],
      weeklyHours: 15,
    },
  },
  {
    name: "Juliana Freitas",
    email: "juliana.freitas@fake.socion.app",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    plan: Plan.TRIAL,
    profile: {
      headline: "Designer de Produto | Ex-Figma | UX para B2B SaaS",
      location: "Florianópolis, SC",
      bio: "Trabalhei no time de design da Figma e da Resultados Digitais. Quero co-fundar um produto voltado para pequenas agências de marketing. Tenho o design e parte do produto mapeado. Busco dev full-stack para começar.",
      trustScore: 74,
      identityScore: 85,
      experienceScore: 80,
      competenceScore: 70,
      reputationScore: 65,
      commitmentScore: 72,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.NONE,
      seekingBusinessType: [BusinessType.SAAS, BusinessType.AGENCY],
      offeringRole: [PartnerRole.PRODUCT, PartnerRole.MARKETING],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.NONE,
      offeringBusinessType: [BusinessType.SAAS],
      weeklyHours: 40,
    },
  },
  {
    name: "Lucas Yamamoto",
    email: "lucas.yamamoto@fake.socion.app",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "Founder & CEO | Saí do zero para R$2M ARR em 18 meses",
      location: "Belo Horizonte, MG",
      bio: "Fundei uma plataforma de logística para e-commerce que chegou a R$2M ARR antes de ser adquirida. Hoje quero fazer de novo, desta vez em AI. Tenho capital próprio e busco sócio técnico com experiência em LLMs.",
      trustScore: 88,
      identityScore: 92,
      experienceScore: 91,
      competenceScore: 85,
      reputationScore: 87,
      commitmentScore: 83,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.UP_TO_50K,
      seekingBusinessType: [BusinessType.AI, BusinessType.SAAS],
      offeringRole: [PartnerRole.SALES, PartnerRole.OPERATIONS],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.ABOVE_50K,
      offeringBusinessType: [BusinessType.AI],
      weeklyHours: 50,
    },
  },
  {
    name: "Mariana Lopes",
    email: "mariana.lopes@fake.socion.app",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    plan: Plan.TRIAL,
    profile: {
      headline: "Advogada Empresarial | Especialista em Contratos de Startup",
      location: "Rio de Janeiro, RJ",
      bio: "10 anos estruturando acordos de sócios, rodadas de investimento e contratos de SaaS. Busco sócio para montar uma LegalTech que automatize contratos para pequenas empresas. Venho com a expertise jurídica e metade do produto desenhado.",
      trustScore: 78,
      identityScore: 96,
      experienceScore: 82,
      competenceScore: 72,
      reputationScore: 76,
      commitmentScore: 65,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY, PartnerRole.PRODUCT],
      seekingAvailability: AvailabilityType.PART_TIME,
      seekingInvestment: InvestmentRange.NONE,
      seekingBusinessType: [BusinessType.SAAS, BusinessType.SERVICES],
      offeringRole: [PartnerRole.LEGAL, PartnerRole.OPERATIONS],
      offeringAvailability: AvailabilityType.PART_TIME,
      offeringInvestment: InvestmentRange.NONE,
      offeringBusinessType: [BusinessType.SAAS],
      weeklyHours: 20,
    },
  },
  {
    name: "Diego Carvalho",
    email: "diego.carvalho@fake.socion.app",
    image: "https://randomuser.me/api/portraits/men/88.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "Engenheiro de ML | Ex-Google Brain | Especialista em LLMs",
      location: "Remoto (base em Recife, PE)",
      bio: "5 anos de Google Brain trabalhando com modelos de linguagem. Publiquei 8 papers e tenho 2 patentes. Quero sair do research e construir um produto real. Busco sócio de negócios que traga visão de mercado e habilidade comercial.",
      trustScore: 93,
      identityScore: 98,
      experienceScore: 96,
      competenceScore: 95,
      reputationScore: 88,
      commitmentScore: 86,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.SALES, PartnerRole.MARKETING, PartnerRole.OPERATIONS],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.UP_TO_10K,
      seekingBusinessType: [BusinessType.AI, BusinessType.SAAS],
      offeringRole: [PartnerRole.TECHNOLOGY],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.NONE,
      offeringBusinessType: [BusinessType.AI],
      weeklyHours: 45,
    },
  },
  {
    name: "Fernanda Oliveira",
    email: "fernanda.oliveira@fake.socion.app",
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    plan: Plan.PRO,
    profile: {
      headline: "CMO | Growth Hacker | Escalo marcas de 0 a 100k usuários",
      location: "Porto Alegre, RS",
      bio: "Já escalei 4 startups como CMO. Especialista em growth orgânico, SEO e comunidade. Tenho uma ideia validada para marketplace de serviços criativos e preciso de sócio técnico. Já tenho 200 pessoas na lista de espera.",
      trustScore: 80,
      identityScore: 88,
      experienceScore: 84,
      competenceScore: 78,
      reputationScore: 77,
      commitmentScore: 74,
      verificationStatus: VerificationStatus.VERIFIED,
      seekingRole: [PartnerRole.TECHNOLOGY, PartnerRole.PRODUCT],
      seekingAvailability: AvailabilityType.FULL_TIME,
      seekingInvestment: InvestmentRange.NONE,
      seekingBusinessType: [BusinessType.MARKETPLACE, BusinessType.SAAS],
      offeringRole: [PartnerRole.MARKETING, PartnerRole.SALES],
      offeringAvailability: AvailabilityType.FULL_TIME,
      offeringInvestment: InvestmentRange.NONE,
      offeringBusinessType: [BusinessType.MARKETPLACE],
      weeklyHours: 40,
    },
  },
]

async function main() {
  console.log("🌱 Seeding fake profiles...")

  for (const u of fakeUsers) {
    const trialEndsAt = new Date()
    trialEndsAt.setDate(trialEndsAt.getDate() + 14)

    const user = await prisma.user.upsert({
      where: { email: u.email },
      update: {},
      create: {
        name: u.name,
        email: u.email,
        image: u.image,
        emailVerified: new Date(),
        plan: u.plan,
        trialEndsAt,
      },
    })

    await prisma.profile.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        ...u.profile,
      },
    })

    console.log(`✅ ${u.name}`)
  }

  console.log(`\n🎉 ${fakeUsers.length} perfis criados com sucesso!`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
